import React from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, XCircle, FileSearch, Sparkles, BookOpen } from 'lucide-react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'ATS Formatting Guide: Fonts, Layouts, and Structure | ResumeATS Pro',
  description: 'Learn the exact formatting rules to make your resume 100% readable by Applicant Tracking Systems.',
};

export default function AtsFormattingGuidePage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-xs text-slate-500">
        <Link href="/" className="hover:text-indigo-600">Home</Link>
        <span>/</span>
        <span className="text-slate-800 dark:text-slate-200 font-medium">Guides</span>
        <span>/</span>
        <span className="text-indigo-600 dark:text-indigo-400">ATS Formatting Guide</span>
      </div>

      {/* Header */}
      <div className="space-y-4">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 text-xs font-semibold">
          <BookOpen className="w-3.5 h-3.5" />
          <span>Formatting & Structure Best Practices</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white tracking-tight leading-tight">
          The Definitive ATS Resume Formatting Guide
        </h1>
        <p className="text-sm sm:text-base text-slate-600 dark:text-slate-300 leading-relaxed">
          Avoid the common design mistakes that cause resumes to get jumbled, misread, or filtered out before a human ever sees them.
        </p>
      </div>

      {/* Content */}
      <div className="space-y-6 text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">
            1. Layout: Single-Column vs Multi-Column
          </h2>
          <p>
            Multi-column layouts (commonly generated by Canva or graphic design tools) look appealing to humans, but ATS engines read text from left-to-right across the entire page. This means the top line of Column 1 gets joined with the top line of Column 2, turning your job descriptions and skill lists into garbled nonsense.
          </p>
          <div className="p-3.5 rounded-xl bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 text-emerald-900 dark:text-emerald-300 font-medium">
            ✓ Golden Rule: Always use a clean, single-column vertical layout with consistent top-to-bottom flow.
          </div>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">
            2. Standard Section Headings
          </h2>
          <p>
            ATS algorithms use pattern matching to find your career sections. If you name your experience section "My Journey" or your skills "What I Bring", the parser may fail to index your qualifications.
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-600 dark:text-slate-400">
            <li><strong>Work Experience:</strong> Use "Work Experience" or "Professional Experience"</li>
            <li><strong>Education:</strong> Use "Education"</li>
            <li><strong>Skills:</strong> Use "Technical Skills" or "Skills & Tools"</li>
            <li><strong>Projects:</strong> Use "Projects" or "Key Technical Projects"</li>
          </ul>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">
            3. Safe Fonts & Character Sets
          </h2>
          <p>
            Stick to universally recognized system fonts such as <strong>Inter, Arial, Calibri, Helvetica, Roboto, or Georgia</strong>. Avoid decorative script fonts, custom icon packages, or graphical star rating bars.
          </p>
        </div>
      </div>

      {/* CTA Box */}
      <div className="p-8 rounded-3xl bg-indigo-600 text-white flex flex-col sm:flex-row items-center justify-between gap-6 shadow-xl">
        <div className="space-y-1 text-center sm:text-left">
          <h3 className="text-xl font-bold">Check your resume’s formatting score</h3>
          <p className="text-xs text-indigo-100">
            Run an instant 28-point formatting and layout audit for free.
          </p>
        </div>
        <Link
          href="/analyze"
          className="px-6 py-3 rounded-xl text-xs font-bold text-indigo-900 bg-white hover:bg-indigo-50 shadow-md transition flex items-center gap-2 flex-shrink-0"
        >
          <FileSearch className="w-4 h-4 text-indigo-600" />
          Test My Resume
        </Link>
      </div>
    </div>
  );
}
